### ISSUE TITLE
Ok stream of `OkErr` operator shows no result tuples when it should in memory visualizer

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#14443]
### What version of Materialize are you using?

v0.26.1-dev (17ecba1d6)

### How did you install Materialize?

Built from source

### What is the issue?

Consider the following view and index definitions, created over a TPC-H database at scale factor 1 with PK and FK indexes over all tables:

```
CREATE VIEW qt AS
SELECT * 
FROM (
    SELECT *
    FROM lineitem
    ORDER BY l_suppkey 
    LIMIT 10);

CREATE DEFAULT INDEX ON qt;
```

In the memory visualizer (http://localhost:6876/memory), we can notice an `OkErr` node at the output of the first `ArrangementFlatMap(scan)` accessing `lineitem`. The two outputs of this node, an `oks` stream and an `errs` stream (see `src/compute/src/render/context.rs` line 559), both appear to be empty, i.e., transiting no rows at all. However, more than 6 million rows from `lineitem` should have been sent through the `oks` stream to the next operator. 

This issue is a request to investigate why the visualization, or its underlying runtime monitoring/logging infrastructure, is not capturing this information.

**Comment by frankmcsherry** [comment]
Seems bisectable by checking the introspection sources
```
mz_message_counts_sent_internal
mz_message_counts_received_internal
```
to see if the data are there. If not it's probably logging, and if yes it's probably visualization.

**Comment by vmarcos** [comment]
From the memory visualizer, we can find the relevant operators and their ids, namely:

- `ArrangementFlatMap(scan) (id: 768, 3s elapsed)`
- `OkErr (id: 772)`
- `TopK (id: 1090, 1m12s elapsed)`

We are particularly interested in why the edge between 772 and 1090 shows no records flowing. To look into the issue, we first obtain the addresses for these operators:

```
tpch=> SELECT dod.dataflow_name, dod.name, dod.id, da.address
FROM mz_dataflow_operator_dataflows dod,
     mz_dataflow_addresses da
WHERE dod.id IN (1090, 772,768) AND
      da.id = dod.id AND
      da.worker = dod.worker;
        dataflow_name         |           name           |  id  | address  
------------------------------+--------------------------+------+----------
 Dataflow: 2.6.qt_primary_idx | TopK                     | 1090 | {23,1,7}
 Dataflow: 2.6.qt_primary_idx | OkErr                    |  772 | {23,1,5}
 Dataflow: 2.6.qt_primary_idx | ArrangementFlatMap(scan) |  768 | {23,1,3}
(3 rows)
```

Given the information above, we can restrict our attention to dataflow 23, region 1. Let's now inspect the corresponding message counts:

```
tpch=> SELECT id, source_node, target_node, sum(sent) as sent
FROM mz_catalog.mz_dataflow_channels AS channels
     LEFT JOIN mz_catalog.mz_message_counts AS counts
         ON channels.id = counts.channel AND channels.worker = counts.source_worker
WHERE
    id IN (
        SELECT id
        FROM mz_catalog.mz_dataflow_addresses
        WHERE address[1] = 23 AND address[2] = 1 AND
              list_length(address) = 2
       
    ) AND
    (source_node IN (3, 5, 7) OR target_node IN (3, 5, 7))
GROUP BY id, source_node, target_node;
  id  | source_node | target_node |  sent   
------+-------------+-------------+---------
  776 |           5 |           6 |        
  777 |           5 |           7 |        
  769 |           1 |           3 |       1
 1092 |           7 |           8 |      10
  773 |           3 |           5 | 6001215
(5 rows)
```

We observe above that the edge between `source_node = 5 (OkErr)` and `target_node = 7 (TopK)` does not have any `sent` messages. As a consequence, we conclude that the bug is not on the visualization itself, but rather on the underlying logging setup for these operators.

**Comment by teskje** [comment]
This is hard to test now because the rendering has changed and `ArrangementFlatMap` doesn't appear in the current dataflow graph anymore. I think this is the same issue as https://github.com/MaterializeInc/materialize/issues/16754, so it should be fixed now as well, but can you think of a way to verify @vmarcos?

**Comment by vmarcos** [comment]
I think this is still reproducible as follows:
```sql
CREATE TABLE t (a int);
INSERT INTO t VALUES (42), (84);
CREATE DEFAULT INDEX ON t;
CREATE VIEW v AS SELECT 42 / a FROM t ORDER BY a LIMIT 1;
CREATE DEFAULT INDEX ON v;
```
Then, it should be possible to observe the problem in the memory visualizer. Here is a query confirming that the introspection data is not what it is supposed to be:
```sql
materialize=> SELECT dod.dataflow_name, dod.name, dod.id, mc.channel_id, dc.from_index, dc.to_index, da.address, da2.address, mc.sent, mc.received
FROM mz_internal.mz_dataflow_operator_dataflows dod,
   mz_internal.mz_dataflow_addresses da,
   mz_internal.mz_dataflow_addresses da2,
   mz_internal.mz_dataflow_channels dc,
   mz_internal.mz_message_counts mc
WHERE dod.dataflow_name LIKE '%v%' AND
   (dod.name LIKE '%OkErr%') AND
--   (dod.id = 11915) AND
   da.id = dod.id AND
   da.worker_id = dod.worker_id AND
   CAST(da2.address AS text) = CAST(da.address[:list_length(da.address) - 1] as text) AND
   da2.worker_id = da.worker_id AND
   dc.id = da2.id AND
   dc.worker_id = da2.worker_id AND
   (dc.from_index = da.address[list_length(da.address):][1] OR dc.to_index = da.address[list_length(da.address):][1]) AND
   mc.channel_id = dc.id
ORDER BY dod.dataflow_name, dod.name, dod.id, dc.from_index, dc.to_index;
        dataflow_name        | name  |  id   | channel_id | from_index | to_index | address  | address | sent | received 
-----------------------------+-------+-------+------------+------------+----------+----------+---------+------+----------
 Dataflow: 1.3.v_primary_idx | OkErr | 11915 | 11916      | 3          | 5        | {49,2,5} | {49,2}  |    2 |        2
 Dataflow: 1.3.v_primary_idx | OkErr | 12234 | 12235      | 8          | 9        | {49,2,9} | {49,2}  |    1 |        1
 Dataflow: 1.3.v_primary_idx | OkErr | 12234 | 12240      | 9          | 11       | {49,2,9} | {49,2}  |    1 |        1
(3 rows)

Time: 13.014 ms
```
Above, the operator with a missing outgoing edge is the one in the commented line. The query shows that, by contrast, the other `OkErr` in the dataflow has both an incoming and an outgoing edge.

**Comment by teskje** [comment]
Here is the issue: The dataflow edges/channels that have missing message counts are special in that they are not "regular" inter-operator channels but edges traveling into and out of regions. It turns out that timely does not perform message logging for these edges.

I have this horrible patch that can be applied to timely's current main and that fixes the issue:

```diff
diff --git a/timely/src/dataflow/operators/enterleave.rs b/timely/src/dataflow/operators/enterleave.rs
index bd9b1f8..7748c84 100644
--- a/timely/src/dataflow/operators/enterleave.rs
+++ b/timely/src/dataflow/operators/enterleave.rs
@@ -21,6 +21,7 @@

 use std::marker::PhantomData;

+use crate::logging::{TimelyLogger, MessagesEvent};
 use crate::progress::Timestamp;
 use crate::progress::timestamp::Refines;
 use crate::progress::{Source, Target};
@@ -82,6 +83,59 @@ impl<G: Scope, T: Timestamp, D: Data, E: Enter<G, Product<<G as ScopeParent>::Ti
     }
 }

+struct LogPusher<P> {
+    pusher: P,
+    channel: usize,
+    counter: usize,
+    index: usize,
+    logging: Option<TimelyLogger>,
+}
+
+impl<P> LogPusher<P> {
+    fn new(pusher: P, channel: usize, index: usize, logging: Option<TimelyLogger>) -> Self {
+        Self {
+            pusher,
+            channel,
+            counter: 0,
+            index,
+            logging,
+        }
+    }
+}
+
+impl<T, D, P> Push<BundleCore<T, D>> for LogPusher<P>
+where
+    D: Container,
+    P: Push<BundleCore<T, D>>,
+{
+    fn push(&mut self, element: &mut Option<BundleCore<T, D>>) {
+        if let Some(bundle) = element {
+            self.counter += 1;
+
+            if let Some(logger) = self.logging.as_ref() {
+                logger.log(MessagesEvent {
+                    is_send: true,
+                    channel: self.channel,
+                    source: self.index,
+                    target: self.index,
+                    seq_no: self.counter - 1,
+                    length: bundle.data.len(),
+                });
+                logger.log(MessagesEvent {
+                    is_send: false,
+                    channel: self.channel,
+                    source: self.index,
+                    target: self.index,
+                    seq_no: self.counter - 1,
+                    length: bundle.data.len(),
+                });
+            }
+        }
+
+        self.pusher.push(element);
+    }
+}
+
 impl<G: Scope, T: Timestamp+Refines<G::Timestamp>, C: Data+Container> Enter<G, T, C> for StreamCore<G, C> {
     fn enter<'a>(&self, scope: &Child<'a, G, T>) -> StreamCore<Child<'a, G, T>, C> {

@@ -99,7 +153,8 @@ impl<G: Scope, T: Timestamp+Refines<G::Timestamp>, C: Data+Container> Enter<G, T
         let input = scope.subgraph.borrow_mut().new_input(produced);

         let channel_id = scope.clone().new_identifier();
-        self.connect_to(input, ingress, channel_id);
+        let pusher = LogPusher::new(ingress, channel_id, scope.index(), scope.logging());
+        self.connect_to(input, pusher, channel_id);
         StreamCore::new(Source::new(0, input.port), registrar, scope.clone())
     }
 }
@@ -131,7 +186,9 @@ impl<'a, G: Scope, D: Clone+Container, T: Timestamp+Refines<G::Timestamp>> Leave
         let output = scope.subgraph.borrow_mut().new_output();
         let (targets, registrar) = TeeCore::<G::Timestamp, D>::new();
         let channel_id = scope.clone().new_identifier();
-        self.connect_to(Target::new(0, output.port), EgressNub { targets, phantom: PhantomData }, channel_id);
+        let egress = EgressNub { targets, phantom: PhantomData };
+        let pusher = LogPusher::new(egress, channel_id, scope.index(), scope.logging());
+        self.connect_to(Target::new(0, output.port), pusher, channel_id);

         StreamCore::new(
             output,
```

I don't propose merging this because I just hacked this together and I have no clue about timely's code organization, but it works. If you build MZ with the patched version of timely, the memory graph shows a bunch of previously empty edges now annotated with message counts.

**Comment by teskje** [comment]
[Relevant Slack thread.](https://materializeinc.slack.com/archives/CMNT2QSBZ/p1676047729007809)

**Comment by teskje** [comment]
This has been fixed in https://github.com/TimelyDataflow/timely-dataflow/pull/507.
