### ISSUE TITLE
storage/sources/postgres: empty results in resumption tests

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22486]
### What version of Materialize are you using?

7eaba7127a

### What is the issue?

Happened in coverage run, but this should only have different timing: https://buildkite.com/materialize/coverage/builds/271 (run for https://github.com/MaterializeInc/materialize/pull/22479, but I think not related to the change?)
```
$ docker compose run testdrive verify-data.td
--- verify-data.td
> SELECT COUNT(*) FROM t1;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 71s
^^^ +++
verify-data.td:10:1: error: non-matching rows: expected:
[["500000"]]
got:
[["0"]]
Poor diff:
+ 0
- 500000

     |
   9 | 
  10 | > SELECT COUNT(*) FROM t1;
     | ^
+++ !!! Error Report
```
I'm not sure if these logs are expected or not:
```
pg-cdc-resumption-materialized-1  | cluster-u2-replica-u2: 2023-10-18T22:15:45.197541Z  WARN mz_postgres_util::desc: Error validating table in publication. Expected: PostgresTableDesc { oid: 16405, namespace: "public", name: "alter_fail_drop_constraint", columns: [PostgresColumnDesc { name: "f1", col_num: Some(1), type_oid: 23, type_mod: -1, nullable: false }], keys: {} } Actual: PostgresTableDesc { oid: 16405, namespace: "public", name: "alter_fail_drop_constraint", columns: [PostgresColumnDesc { name: "f1", col_num: Some(1), type_oid: 23, type_mod: -1, nullable: true }], keys: {} }
pg-cdc-resumption-materialized-1  | cluster-u2-replica-u2: 2023-10-18T22:15:45.323670Z  INFO mz_postgres_util::tunnel: connecting task_name=postgres_publication_info address=materialize@toxiproxy:5432/postgres
pg-cdc-resumption-materialized-1  | cluster-u2-replica-u2: 2023-10-18T22:15:45.336875Z  INFO mz_postgres_util::tunnel: connected task_name=postgres_publication_info address=materialize@toxiproxy:5432/postgres
pg-cdc-resumption-materialized-1  | cluster-u2-replica-u2: 2023-10-18T22:15:46.383527Z  INFO mz_storage::healthcheck: Health transition for source u10: Some(Starting) -> Some(Stalled { error: "postgres: incompatible schema change: source table alter_fail_drop_constraint with oid 16405 has been altered", hints: {}, namespaced_errors: {Postgres: "incompatible schema change: source table alter_fail_drop_constraint with oid 16405 has been altered"} })
pg-cdc-resumption-materialized-1  | cluster-u2-replica-u2: 2023-10-18T22:15:47.721891Z  INFO mz_storage::healthcheck: Health transition for source u7: Some(Starting) -> Some(Stalled { error: "postgres: incompatible schema change: source table alter_fail_drop_col with oid 16402 has been altered", hints: {}, namespaced_errors: {Postgres: "incompatible schema change: source table alter_fail_drop_col with oid 16402 has been altered"} })
pg-cdc-resumption-materialized-1  | cluster-u2-replica-u2: 2023-10-18T22:15:47.760971Z  INFO mz_storage::healthcheck: Health transition for source u8: Some(Starting) -> Some(Stalled { error: "postgres: incompatible schema change: source table alter_fail_drop_constraint with oid 16405 has been altered", hints: {}, namespaced_errors: {Postgres: "incompatible schema change: source table alter_fail_drop_constraint with oid 16405 has been altered"} })
```
@sploiselle Do you have any idea about this failure? Previously we had partial results, but I'm not sure if we had 0 before: https://github.com/MaterializeInc/materialize/issues/19617

ci-regexp: verify-data.td:12:1: error: non-matching rows: expected

**Comment by sploiselle** [comment]
This is almost certainly due to #22163. I'll have to dig into why the snapshot wouldn't have completed--the source status history most likely have information about what went awry if something did. As for the logs, those are expected artifacts of the test.

**Comment by sploiselle** [comment]
@def- Is there a way to check if this has occurred recently?

**Comment by def-** [comment]
@sploiselle Now something similar happened again: https://buildkite.com/materialize/tests/builds/74983#018d7f3d-cab6-44ec-ab3b-3964e400de9b
```
ValueError: Source alter_fail_drop_col is expected to be running/created, but is stalled, error: postgres: incompatible schema change: source table alter_fail_drop_col with oid 16402 has been altered, details: {'namespaced': {'postgres': 'incompatible schema change: source table alter_fail_drop_col with oid 16402 has been altered'}}
```

**Comment by sploiselle** [comment]
@def- The linked-to test is a bug in source error reporting. That source needs to be dropped at the end of the test because it's expected to be in a failed state but we (incorrectly) do not persist the last-seen status for sources across restarts. This is fixed in #24531

**Comment by benesch** [comment]
@def- it sounds like we haven't seen the issue in the description in a while, is that right?

**Comment by def-** [comment]
I'm not sure. Let's close it for now, and I'll reopen if this happens in CI again.

**Comment by sploiselle** [comment]
@def- and I looked at this today––didn't repro locally. Dennis has a suspicion that this might be failing in CI because of `qemu-user-static`'s additional latency.

**Comment by def-** [comment]
We can see if after merging https://github.com/MaterializeInc/materialize/pull/25970 this still occurs.

**Comment by benesch** [comment]
@def- have we seen this recently in CI?

**Comment by def-** [comment]
I have verified using `bin/buildkite-step-insights --pipeline tests --build-step-key pg-cdc-resumption --branch main --build-step-state failed` and `bin/buildkite-step-insights --pipeline coverage --build-step-key pg-cdc-resumption --branch '*' --build-step-state failed`. And we haven't seen this since https://github.com/MaterializeInc/materialize/pull/25970 landed, so considering this fixed. Sorry for the noise!

**Comment by benesch** [comment]
Woohoo! Glad to have at least one of these correctness-looking flakes knocked out.
