### ISSUE TITLE
mysql: sources can have a 3-second delay in receiving their most recent update

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#24630]
### What version of Materialize are you using?

dd9182f669

### What is the issue?

The following test snippet, which fails because `SELECT * FROM t1;` only returns a single row instead of two, indicates that sources do not receive updates after they are created.

```
$ set-sql-timeout duration=1s
$ set-max-tries max-tries=3

$ postgres-execute connection=postgres://mz_system:materialize@${testdrive.materialize-internal-sql-addr}
ALTER SYSTEM SET enable_mysql_source = true

> CREATE SECRET mysqlpass AS '${arg.mysql-root-password}'
> CREATE CONNECTION mysql_conn TO MYSQL (
    HOST mysql,
    USER root,
    PASSWORD SECRET mysqlpass
  )

$ mysql-connect name=mysql url=mysql://root@mysql password=${arg.mysql-root-password}

$ mysql-execute name=mysql
DROP DATABASE IF EXISTS public;
CREATE DATABASE public;
USE public;

CREATE TABLE t1 (f1 INTEGER);

INSERT INTO t1 VALUES (1);

> CREATE SOURCE mz_source
  FROM MYSQL CONNECTION mysql_conn
  FOR ALL TABLES;

> SELECT COUNT(*) > 0 FROM t1;
true

$ mysql-execute name=mysql
INSERT INTO t1 SELECT * FROM t1;

> SELECT * FROM t1;
1
1
```

```
error: non-matching rows: expected:
[["1"], ["1"]]
got:
[["1"]]
```

**Comment by nrainer-materialize** [comment]
Adding a `COMMIT;` to MySQL does not change anything by the way. Auto-commit is on by default as far as I know.

**Comment by rjobanp** [comment]
@nrainer-materialize thanks for the report, I was able to replicate this using your snippet. However if you update
```
$ set-max-tries max-tries=3
```
to
```
$ set-max-tries max-tries=20
```
it resolves the issue because the dataflow does eventually catch up to contain the new update.

The reason is a quirk in how we've implemented the frontier advancement in the MySQL replication operator at the moment, I'll try to explain:
- Since we haven't yet implemented comprehensive event-handling for all event-types that we may receive on the MySQL replication stream, we are being somewhat conservative about how we advance the frontier when receiving a "Rows Event" which contains changes to table rows. This is because we aren't yet sure if MySQL might send other event-types that need to be committed at the same timestamp that the "RowsEvent" was received with.
- The current implementation advances the frontier to a point beyond the previous "RowsEvent" on each new "RowsEvent" we receive on the replication stream. So if we receive lots of updates back-to-back, they are exposed very quickly.
- However the 'last' update we received won't get exposed to the dataflow immediately so nothing comes after it. So we've configured MySQL to send us a 'heartbeat' message after 3-seconds of no other updates, which we currently use to advance the frontier again and flush the last transaction we received.
- This is why we need to wait a little longer than that 3-second period to see the last update received by the source, which is why adjusting the testdrive retry logic fixes the issue.
- I'm fairly confident that in the future we can just advance the frontier immediately after each "RowsEvent", but just haven't gotten around to validate that MySQL definitely won't send other updates that need to be attached to the same timestamp. I plan to dig into this in the next week or so.

Let me know if that makes sense -- I'm happy to chat live if needed. Maybe we can reword this issue to say "mysql: sources can have a 3-second delay in receiving their most recent update"

**Comment by nrainer-materialize** [comment]
Makes sense, thank you!
The workaround works for me!

**Comment by nrainer-materialize** [comment]
I believe I have just experienced this with `$ set-max-tries max-tries=20` in a scenario with a handful of tables.

**Comment by nrainer-materialize** [comment]
> I believe I have just experienced this in a scenario with a handful of tables with:
> 
> ```
> $ set-sql-timeout duration=1s
> $ set-max-tries max-tries=20
> ```

The issue does still occur with this configuration in several places. You can find those by searching https://github.com/MaterializeInc/materialize/pull/24733 for `TODO: #24630`.

**Comment by rjobanp** [comment]
Updated notes from recent learnings related to this issue:

- Large transactions/statements and multi-table transactions in the replication stream are broken up into multiple `RowsEvent` events such that we cannot assume there is a 1-to-1 correspondence with a GTID and a `RowsEvent` we receive.
- Therefore we cannot advance the frontier beyond the current GTID until we receive a subsequent-GTID or the 3-second heartbeat message, which is what we're currently doing.
- However we discovered that there is a `STMT_END` flag on the `RowsEvent` events that might tell us if the event is the 'last' one for a given statement/transaction. If this applies to row-based replication and all transaction/statement-types it could allow us to advance the frontier to the next GTID immediately upon receiving the event annotated with this flag, without needing to wait the 3-seconds until the heartbeat message.
- Unfortunately this flag struct https://docs.rs/mysql_common/latest/mysql_common/binlog/consts/struct.RowsEventFlags.html is not exposed in a public method available to us, so we need to fork the `mysql-common` crate to add support to access it.

The next steps to attempt to address this issue:
- Fork the `mysql-common` crate and add a public method to access the flags on a `RowsEvent` message.
- Test various statement/transaction scenarios to ensure the `STMT_END`  flag ensures we will receive no other events for the current GTID
- Advance the frontier to the next GTID once we see that flag on an event and remove the heartbeat advancement logic

**Comment by rjobanp** [comment]
Update -- we thought that the `STMT_END` flag on `RowsEvent` events could be used to identify the last event corresponding to a given GTID, but this is unfortunately not the case. An implementation was attempted in #26223 , more details are in that PR.

So I think this issue may be impossible to close with the information we receive from MySQL's replication stream, unfortunately. Our best option may be setting the heartbeat interval to something like 1-second instead of 3-seconds, but I haven't looked into whether there would be any significant performance implications if we did that.

**Comment by rjobanp** [comment]
Ah, good find! For some reason I thought those events only applied in non-GTID configured replication streams, but I may have read an out of date article or misunderstood something. I'll open a PR to use this instead!
